### PR TITLE
Feature/auto formatting

### PR DESCRIPTION
**Pull request by Ruchitakheni**

### CODE REVIEW

**Comment by ChiragMoradiya** [comment]
- Why do we do pattern validation on 2 different events: `input` & `keypress`. Shouldn't that be only on `keypress`?
- Can we rename proprty `isDense` to `dense`?
- Rename `highLightOnChanged` to `highlightChanged`
- Rename `isValueChanged` to `valueComparator`
- Rename `formattedValueGetter` to `valueFormatter`.
- Rename `focusedValueGetter` to `valueDeformatter`. OR We can remove this feature completely. I don't think it's much useful.
- Rename `hasClickableIcon` to `clickableIcon`.
- Rename `_isValueUpdated` to `_valueUpdated`.

**Comment by Ruchitakheni** [comment]
> * Why do we do pattern validation on 2 different events: `input` & `keypress`. Shouldn't that be only on `keypress`?

We need to do validation on `input` because we don't receives `keypress` event on value paste.

**Comment by Ruchitakheni** [comment]
> * Possibly we need to split: `formattedValueGetter` to `valueParser` and `textFormatter`.

I think we don't need it. We can discuss it.

**Comment by ChiragMoradiya** [comment]
If possible show 'ripple' effect for clickable icon. If it's hard log separate card so we don't forget.

**Pull request closed without merging**
